- name: "add hosts to /etc/hosts"
  lineinfile: dest=/etc/hosts regexp='.*{{ hostvars[item]['inventory_hostname'] }}(\s*)$' line='{{ hostvars[item]['ansible_host'] }}        {{ hostvars[item]['inventory_hostname'] }}'
  with_items: "{{ groups[hdfs_hosts_group_name] }}"
